services:
  orders-db:
    image: postgres:14
    container_name: orders-database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: alejandro
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb


    